### PR TITLE
Feature/creating library for model classes

### PR DESCRIPTION
**Pull request by XanatosX**
# What did change

Moving the logic for the file conversion to a library so that a ui can be created in the future. At the moment the cli application is not changed at all.

## Why was it changed

There was an idea in the chat that there should be a ui in the future for single file changes. To achive this the cli and conversion logic should be separated.

## Changelog

* Adding .net standard library with code for conversion
* Adding bitmap nuget reference for .net standard (Need to be checked if the results are identical)
* Raised .net version from 4.6 to 4.7.2

## IMPORTANT: What needs to be done before merging

Since I'm missing the game just yet I cannot test if the still works as expected. The build was successful but I don't know if the changes did break some functions

### CODE REVIEW

**Comment by XanatosX** [comment]
Looks like the new files are not added properly I need to check this again.

Maybe the android github app is not listing them correctly

**Comment by XanatosX** [comment]
Now this should work the project was kind of "broken" for me I was forced to recreate it.
We still need to test it creating the build and starting the cli application did work on my machine

**Comment by nyfrk** [comment]
Im sorry but i cannot get it to build. What exactly do we have to do to make it build again?

I installed the devoloper pack 4.7.2 from [here](https://dotnet.microsoft.com/download/visual-studio-sdks).

Then I opened the solution (S4GFX.sln) in Visual Studio (I tried VS 2017 and VS 2019) and had to migrate it. So far so good, but when opening the solution the S4GFXFramework project does not load and thus preventing me from doing a build. Did I miss something? Error is "missing Microsoft.NET.Sdk".

I therefore installed [this](https://www.microsoft.com/de-de/download/details.aspx?id=19988). But it does not change anything. 

Maybe a readme with all the dependencies / steps to get it running would be nice. Especially as it seems to require more effort to get it building now.

**Comment by XanatosX** [comment]
I did create a issue for the readme request #6 

That's really good feedback on my machine this did work like a charm without any changes. Do you miss the .netcore 3.1 sdk? The other possibility is that I did broke the project by restructuring it.

And there is a nuget dependecy now because of the .net standard framework. I will take a look more into detail about the problem tomorrow.

I did use Visual Studio Community 2019 without any additional plugins installed. I need to talk with @WizzardMaker if he wants to use .NET framework ("Old" type) libraries or .NET standard (Current type). The advantage of .net standard is that it can be used with .net core but since there is not working version of this game for linux or mac this should be irrelevant.

It looks like this on my computer

grafik

Didn't checked it on another device.

Edit: Added link to newly created issue
Edit2: Added additional hints for building

**Comment by XanatosX** [comment]
@WizzardMaker  Maybe we should add a github action building the project on each "pull-request"  #7 so we can verify that the build is working correctly with new commits?

We could extend this later on so that the whole project is getting builded and uploaded ready for downloading.

Edit: Added issue for this idea

**Comment by nyfrk** [comment]
I already had .NET CORE 3.1 SDK installed. I get the following upgrade dialog when opening it for the first time:

image

When doing the migration (by clicking ok) I get this:

image

and the following line in the console:

`H:\S4GFX\S4GFXFramework\S4GFXFramework.csproj : error  : Das angegebene SDK "Microsoft.NET.Sdk" wurde nicht gefunden.  H:\S4GFX\S4GFXFramework\S4GFXFramework.csproj
`

In the solution explorer it looks therefore like this:

image

I get the very same behaviour when using Visual Studio 2017. Sorry for the localized screenshots.

**Comment by XanatosX** [comment]
After sleeping about this problem and talking to the mainainer a little bit I think we should use .net framework libraries instead of .net standard so we can use a more spread .net 4.6

But I will wait for him to finally decide which way we should go.

**Comment by XanatosX** [comment]
> 
> 
> I already had .NET CORE 3.1 SDK installed. I get the following upgrade dialog when opening it for the first time:
> 
> image
> 
> When doing the migration (by clicking ok) I get this:
> 
> image
> 
> and the following line in the console:
> 
> `H:\S4GFX\S4GFXFramework\S4GFXFramework.csproj : error : Das angegebene SDK "Microsoft.NET.Sdk" wurde nicht gefunden. H:\S4GFX\S4GFXFramework\S4GFXFramework.csproj `
> 
> In the solution explorer it looks therefore like this:
> 
> image
> 
> I get the very same behaviour when using Visual Studio 2017. Sorry for the localized screenshots.

@nyfrk
Could you try to give the following branch https://github.com/XanatosX/S4GFX/tree/feature/using-dotnet-framework-library a try?

I did change for testing the .NET Standard library to a .NET Framework library and changed the version back to 4.6.

@WizzardMaker 
After changing this back to pure C# the NuGet requirement is for the drawing library is gone as well which is good I think. I would like to use the "new" branch if the build is working and the functionality is unchanged. As we talked yesterday, you are totally right it makes a whole lot more sense to keep the code as simple and useful as possible.

Edit: Added link to user account
Edit2: Adding additional information to this PR

**Comment by nyfrk** [comment]
@XanatosX 

Yes the using-dotnet-framework-library branch works fine for me. No migration was required at all now. 👍

**Comment by XanatosX** [comment]
The PR should be ready to merge now @WizzardMaker please check if I did correctly include your changes from PR #8. It is building on my side but I do not know how to test it.

**Comment by WizzardMaker** [comment]
:+1:
Works!

**Pull request merged**
